site_name: "JDG — ИП в Польше"
site_description: "Гайд по регистрации и ведению JDG (ИП) в Польше"
site_url: https://sobolevbel.github.io/jdg/
repo_url: https://github.com/sobolevbel/jdg

theme:
  name: readthedocs

nav:
  - Главная: index.md
  - PESEL: pesel.md
  - Profil Zaufany: pz.md
  - Регистрация JDG: registration.md
  - ZUS: zus.md
  - Переход на Obniżone składki ZUS: zus_obnizone_skladki.md
  - Налоги: taxes.md
  - Декларации: declarations.md
  - Легализация: legalization.md
  - Польский лад: polski_lad.md
  - Рабочий процесс: workflow.md
  - F.A.Q.: faq.md

markdown_extensions:
    - toc:
        permalink: 
