name: Check Markdown links

on:
  pull_request:
    paths:
      - "**.md"
      - ".github/workflows/markdown_link_check.yml"
      - ".github/workflows/markdown_link_check_config.json"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: install markdown-link-check
      run: npm i -g markdown-link-check

    - name: run link check
      run: >-
        find .
        -name '*.md'
        -not -path './node_modules/*'
        -exec markdown-link-check '{}'
        --config .github/workflows/markdown_link_check_config.json -v ';'

    # - uses: gaurav-nelson/github-action-markdown-link-check@v1
    #   with:
    #     use-quiet-mode: 'no'
    #     use-verbose-mode: 'yes'
    #     config-file: '.github/workflows/markdown_link_check_config.json'
