name: Check Markdown Links

on:
  pull_request:
    paths:
      - "**.md"
      - ".github/workflows/markdown_link_check.yml"
      - ".github/workflows/markdown_link_check_config.json"

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install markdown-link-check
      run: npm install -g markdown-link-check

    - name: Run link check
      run: |
        find . -name '*.md' \
          -not -path './node_modules/*' \
          -not -path './.git/*' \
          -exec markdown-link-check '{}' \
          --config .github/workflows/markdown_link_check_config.json \
          --verbose \;
